# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [102]:
import numpy as np

#### Create an array of 10 zeros

In [103]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [104]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [105]:
#1
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [106]:
#2
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [107]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [108]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [109]:
#1
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
#2
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [111]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [112]:
np.random.rand()

0.6391575695881065

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

we mentioned that the numpy.random.randn() generates samples from the **standard normal distribution**, which means it generates random numbers with a  **mean of 0 and a standard deviation of 1.**

The range of values returned by numpy.random.randn() is theoretically unbounded, but in practice, most of the generated values will be within a few standard deviations of the mean. Specifically, approximately **99.7%** of the generated values will fall within t**hree standard deviations of the mean.** (which corresponds to the range from **-3 to 3**.)

In [113]:
arr=np.random.randn(25)
arr

array([-0.68738175,  0.80372849,  0.00514849, -1.82858094,  0.59165873,
        0.28772697, -0.06045505,  0.97569746,  0.970112  ,  0.68421299,
       -0.37975864,  0.10712684,  0.43981762,  0.88222702, -0.77459112,
        0.48348147,  1.48164983,  0.54777389,  1.0422592 ,  1.35658614,
       -0.09850811, -0.81371363, -0.15283077,  0.45771082, -1.18709804])

#### generate 20 random numbers following a normal distribution and ensure that they fall within the range of -2 to 2.

---



In [114]:
arr=np.random.normal(0,1,20)
arr=np.clip(arr, -2, 2)
arr

array([-1.47303237,  1.94831705, -0.00909511,  0.54815904,  0.55844779,
        1.40455632, -0.15749481, -0.86476071,  0.15505196, -0.08420028,
       -0.44299519,  0.66271052,  0.25532643,  0.38441193,  0.05675519,
        0.21435662,  0.21570212, -0.49845933,  0.56948308, -1.45110342])

Create the following matrix (as shown below).



```
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]

[[ 0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]
 [ 1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2. ]
 [ 2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3. ]
 [ 3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4. ]
 [ 4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5. ]
 [ 5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6. ]
 [ 6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7. ]
 [ 7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8. ]
 [ 8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9. ]
 [ 9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9 10. ]]

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

```










In [115]:
arr=np.arange(0.01,1.01,0.01).reshape(10,10)
print(arr,end="\n\n")
print(arr*10,end="\n\n")
print(arr*100)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]

[[ 0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]
 [ 1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2. ]
 [ 2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3. ]
 [ 3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4. ]
 [ 4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5. ]
 [ 5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6. ]
 [ 6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7. ]
 [ 7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8. ]
 [ 8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8

#### Create an array of 20 linearly spaced points between 0 and 1:

In [116]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix **outputs**:

In [117]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [118]:
# show all rows without the first and second row, and all columns without the first column
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [119]:
# Show "20" element in the matrix
mat[3,4]

20

In [120]:
# show the second column for the top 3 rows
mat[0:3,1]

array([ 2,  7, 12])

In [121]:
# show the fifth row
mat[4]

array([21, 22, 23, 24, 25])

In [122]:
# show all rows after the thrid row
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [123]:
mat.sum()

325

Get the standard deviation of the values in 'mat' (you can check what the standard deviation is, here: https://byjus.com/maths/standard-deviation/, and we will talk about these concepts in more detail).

In [124]:
segma_f_xi2=(mat**2).sum()
segma_2_f_xi=(mat.sum())**2
variance=(1/24)*(segma_f_xi2-((1/25)*(segma_2_f_xi)))
variance**0.5

7.359800721939872

In [125]:
#build-in function
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [126]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

# Great Job!